### ISSUE TITLE
Feature Request: add support for ESLint (JS)

### ISSUE THREAD

**Issue by keradus** [sk-/git-lint#68]

**Comment by sk-** [comment]
Hi @keradus, could you briefly list the benefits of this inter compared to `jshint` or `gjslint`?

Feel free to send a PR, including the changes. It is fairly easy to add support for a new linter. Check the file https://github.com/sk-/git-lint/blob/master/gitlint/configs/config.yaml

**Comment by keradus** [comment]
There is no need to copy the comparision. One may find it online, eg http://www.sitepoint.com/comparison-javascript-linting-tools/

I do not say that ESLint is the best linter for JS, but currently there are five main linters for JS (you missing ***ESLint***, ***JSCS*** and good old ***JSLint***).
Non of them do all the job, many use multiple linters at once (like JSHint + JSCS - first one even remove some linting rules and redirect users to start using JSCS), and it's just great to give people the choice.

I won't be able to help with PR, but also I will respectfully accept if you decide to refuse that feature request.

**Comment by JHSaunders** [comment]
If you add this to your `.gitlint.yaml`

```yaml
# Sample output:
#  37:1   error  Expected indentation of 2 spaces but found 0  indent
eslint:
  extensions:
  - .js
  command: eslint
  filter: "(?P<line>\\d+):(?P<column>\\d+)\\s+error\\s+(?P<message>.+)"
  installation: "npm install -g eslint"
```
and have a `.eslintrc.js|json|yaml` in your project root you can use eslint with git-lint. I will make a pull request for this when I get a moment.

**Comment by ilkovalc** [comment]
@JHSaunders I was trying to use your method, but unfortunately didn't succeed. 
here is the diff of file I've changed
 `var a_aDDD_a = 3`
and this is the config of eslint file that I've get using eslint --init command.
`{
    "extends": "airbnb",
    "plugins": [
        "react",
        "jsx-a11y",
        "import"
    ]
}`

and this is what I've got: 
`Linting file: .eslintrc.json`
`OK`

`Linting file: .gitlint.yaml`
`OK`

`Linting file: js/pos/app.js`
`OK`

`Linting file: package.json`
`OK`

It seems like eslint doesn't see any errors, but according to config it should

**Comment by Fliu777** [comment]
@JHSaunders @ilkovalc seems like an issue with the filter, not sure how to fix yet, but passing in --debug gets messages to print at least

**Comment by JHSaunders** [comment]
Okay this is now working correctly for me

```yaml
# Sample output:
#  37:1   error  Expected indentation of 2 spaces but found 0  indent
eslint:
  extensions:
  - .js
  command: eslint
  filter: "(?P<line>{lines}):(?P<column>\\d+)\\s+error\\s+(?P<message>.+)"
  installation: "npm install -g eslint"
```

I hadn't really understood the filter regex correctly. This gives me output like this:

```
Linting file: apps/kms/knowledge/ide/static/js/kms/knowledge/ide/DataSourceView.js
line 64, col 23: Missing semicolon                             semi
line 69, col 38: 'steve' is defined but never used             no-unused-vars
ERROR
```

Just to make sure it is not version issue I have the following eslint version
```
$ eslint --version
v3.13.1
```

make sure you can run `eslint` manually and it picks out the correct errors for your file.
